spring:
  application:
    name: toeic-part1-app
  main:
    allow-circular-references: true
  
  datasource:
    url: ${DATABASE_URL:jdbc:h2:file:./data/toeic_part1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT:org.hibernate.dialect.H2Dialect}
        '[format_sql]': true
  
  web:
    resources:
      static-locations: classpath:/static/
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

'jwt':
  secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    '[com.example.toeic]': DEBUG
    org.springframework.security: DEBUG 